# Generated by Django 3.2.22 on 2023-11-19 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_comment_profile_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
