# Generated by Django 3.2.22 on 2023-11-19 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0003_comment_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='profile_id',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='profile_image',
        ),
    ]
